// Crypto Bento Cards 配置数据
export interface CryptoCard {
  id: string;
  title: string;
  content: string;
  image: string;
  titleButton: string;
}

export const cryptoCards: CryptoCard[] = [
  {
    id: "private-key",
    title: "Private Key",
    content: "Secure wallet access with cryptographic key management.",
    image: "/crypto-images/private-key.png",
    titleButton: "Generate key",
  },
  {
    id: "blockchain-basics",
    title: "Blockchain Basics",
    content: "Visualize decentralized data structure with linked blocks.",
    image: "/crypto-images/blockchain-basics.png",
    titleButton: "Explore blocks",
  },
  {
    id: "crypto-exchange",
    title: "Crypto Exchange",
    content: "Enable seamless trading between various cryptocurrencies.",
    image: "/crypto-images/crypto-exchange.png",
    titleButton: "Start trading",
  },
  {
    id: "multi-coin-wallet",
    title: "Multi-Coin Wallet",
    content: "Store and manage diverse cryptocurrency assets securely.",
    image: "/crypto-images/multi-coin-wallet.png",
    titleButton: "Create wallet",
  },
  {
    id: "crypto-payment",
    title: "Crypto Payment",
    content: "Facilitate instant transactions via QR code scanning.",
    image: "/crypto-images/crypto-payment.png",
    titleButton: "Scan QR",
  },
  {
    id: "crypto-mining",
    title: "Crypto Mining",
    content: "Generate new coins through computational problem-solving.",
    image: "/crypto-images/crypto-mining.png",
    titleButton: "Mine now",
  },
  {
    id: "market-volatility",
    title: "Market Volatility",
    content: "Track real-time price fluctuations across crypto markets.",
    image: "/crypto-images/market-volatility.png",
    titleButton: "View trends",
  },
  {
    id: "crypto-security",
    title: "Crypto Security",
    content: "Implement advanced protection for digital asset storage.",
    image: "/crypto-images/crypto-security.png",
    titleButton: "Secure assets",
  },
  {
    id: "smart-contracts",
    title: "Smart Contracts",
    content: "Automate agreements with self-executing blockchain code.",
    image: "/crypto-images/smart-contracts.png",
    titleButton: "Deploy contract",
  },
  {
    id: "decentralized-network",
    title: "Decentralized Network",
    content: "Visualize peer-to-peer connections in global crypto networks.",
    image: "/crypto-images/decentralized-network.png",
    titleButton: "Join network",
  },
  {
    id: "token-fractioning",
    title: "Token Fractioning",
    content: "Divide assets into tradable fractions for accessibility.",
    image: "/crypto-images/token-fractioning.png",
    titleButton: "Divide token",
  },
  {
    id: "crypto-atm",
    title: "Crypto ATM",
    content: "Enable physical access points for buying and selling crypto.",
    image: "/crypto-images/crypto-atm.png",
    titleButton: "Find ATM",
  },
  {
    id: "proof-of-stake",
    title: "Proof of Stake",
    content: "Validate transactions through coin ownership and staking.",
    image: "/crypto-images/proof-of-stake.png",
    titleButton: "Stake coins",
  },
  {
    id: "initial-coin-offering",
    title: "Initial Coin Offering",
    content: "Launch new cryptocurrencies with token-based fundraising.",
    image: "/crypto-images/initial-coin-offering.png",
    titleButton: "Invest now",
  },
  {
    id: "market-analysis",
    title: "Market Analysis",
    content: "Utilize AI-driven tools for in-depth cryptocurrency trend analysis.",
    image: "/crypto-images/market-analysis.png",
    titleButton: "Analyze trends",
  },
  {
    id: "cross-chain-bridge",
    title: "Cross-Chain Bridge",
    content: "Facilitate asset transfers between different blockchains.",
    image: "/crypto-images/cross-chain-bridge.png",
    titleButton: "Transfer assets",
  },
  {
    id: "cold-storage",
    title: "Cold Storage",
    content: "Implement secure cold storage solutions for large funds.",
    image: "/crypto-images/token-fractioning-1.png",
    titleButton: "Store securely",
  },
  {
    id: "crypto-staking",
    title: "Crypto Staking",
    content: "Lock tokens to support network operations and earn rewards.",
    image: "/crypto-images/crypto-staking.png",
    titleButton: "Start Staking",
  },
  {
    id: "crypto-rewards",
    title: "Crypto Rewards",
    content: "Implement loyalty programs with cryptocurrency incentives.",
    image: "/crypto-images/crypto-rewards.png",
    titleButton: "Earn rewards",
  },
  {
    id: "blockchain-explorer",
    title: "Blockchain Explorer",
    content: "Analyze and track all transactions on the blockchain.",
    image: "/crypto-images/blockchain-explorer.png",
    titleButton: "Search chain",
  },
  {
    id: "crypto-airdrop",
    title: "Crypto Airdrop",
    content: "Receive free tokens through promotional distributions.",
    image: "/crypto-images/crypto-airdrop.png",
    titleButton: "Claim tokens",
  },
  {
    id: "hardware-wallet",
    title: "Hardware Wallet",
    content: "Secure offline storage for cryptocurrency private keys.",
    image: "/crypto-images/hardware-wallet.png",
    titleButton: "Setup wallet",
  },
  {
    id: "network-latency",
    title: "Network Latency",
    content: "Monitor and optimize blockchain transaction processing times.",
    image: "/crypto-images/network-latency.png",
    titleButton: "Check speed",
  },
  {
    id: "liquidity-pool",
    title: "Liquidity Pool",
    content: "Provide assets to decentralized exchanges for trading depth.",
    image: "/crypto-images/liquidity-pool.png",
    titleButton: "Add liquidity",
  },
  {
    id: "token-minting",
    title: "Token Minting",
    content: "Create and issue new cryptocurrency tokens on blockchain.",
    image: "/crypto-images/token-minting.png",
    titleButton: "Mint tokens",
  },
  {
    id: "token-swap",
    title: "Token Swap",
    content: "Facilitate easy conversion between different crypto tokens.",
    image: "/crypto-images/token-swap.png",
    titleButton: "Swap token",
  },
  {
    id: "crypto-card",
    title: "Crypto Card",
    content: "Spend cryptocurrency at traditional point-of-sale systems.",
    image: "/crypto-images/crypto-card.png",
    titleButton: "Order card",
  },
  {
    id: "defi-dashboard",
    title: "DeFi Dashboard",
    content: "Monitor decentralized finance investments and yields.",
    image: "/crypto-images/defi-dashboard.png",
    titleButton: "View portfolio",
  },
  {
    id: "crypto-yield",
    title: "Crypto Yield",
    content: "Earn passive income through staking and lending protocols.",
    image: "/crypto-images/crypto-yield.png",
    titleButton: "Start earning",
  },
  {
    id: "governance-token",
    title: "Governance Token",
    content: "Participate in blockchain project decisions with tokens.",
    image: "/crypto-images/governance-token.png",
    titleButton: "Cast vote",
  },
];
