import { ProductPageProps } from "../research/ProductPage";

export type DetectionModelType =
  | "deepfakes"
  | "ai-generated-media"
  | "voice-clones";

export const detectionModelsConfig: Record<
  DetectionModelType,
  ProductPageProps
> = {
  deepfakes: {
    metadata: {
      title: "Deepfakes (Faceswap) — ScamAI",
      description:
        "Detect deepfakes and faceswaps with ScamAI's advanced real-time detection.",
    },

    hero: {
      category: "Deepfake Detection",
      headline: "Defending the Truth in Human Face",
      subtitle: "Real-Time Deepfake Detection",
      description: "",
      tags: ["GenAI", "Deepfake", "Faceswap"],
      visual: {
        type: "video",
        src: "/deepfake_scamai.webm",
      },
    },
    problemSection: {
      headline: 'The Threat: "Seeing is Believing" Is a Thing of the Past',
      description: "",
      visual: {
        type: "image",
        src: "/deeepfake-detection.png",
        alt: "Deepfake detection interface showing analysis results",
      },
      valueProps: [],
    },
    threatLandscape: {
      headline: "",
      description: "",
      keyThreats: [],
      dataPoint: "",
    },
    solution: {
      productName: "",
      headline: "",
      description: "",
      coreDimensions: [],
      outputDescription: "",
    },
    advantages: {
      headline: "",
      items: [],
    },
    useCases: {
      headline: "",
      items: [],
    },
    apiSection: {
      headline: "",
      description: "",
      apiDocumentation: {
        text: "",
        href: "",
      },
    },
    cta: {
      headline: "Take the Next Step",
      description:
        "Protect your organization with advanced deepfake detection.",
      primary: { text: "Request a Demo", href: "/demo" },
    },
    backgroundImage: "/deepfake.webp",
  },

  "ai-generated-media": {
    metadata: {
      title: "AI Image Detection — ScamAI",
      description:
        "Detect AI-generated images and videos with ScamAI's advanced detection technology.",
    },

    hero: {
      category: "AI-Generated Media Detection",
      headline: "Detect AI-Generated Images and Video",
      subtitle: "Verifying Reality in a Synthetic World",
      description: "",
      tags: ["GenAI", "Synthetic Media", "Detection"],
      visual: {
        type: "image",
        src: "/fake-news.jpg",
        alt: "Examples of AI-generated fake news images showing fabricated content",
      },
    },
    problemSection: {
      headline: "The Threat: Is Any Image\nReal Anymore?",
      description: "",
      visual: {
        type: "image",
        src: "/gen-ai-detected.png",
        alt: "AI detection interface showing AI-generated content identification results",
      },
      valueProps: [],
    },
    threatLandscape: {
      headline: "",
      description: "",
      keyThreats: [],
      dataPoint: "",
    },
    solution: {
      productName: "",
      headline: "",
      description: "",
      coreDimensions: [],
      outputDescription: "",
    },
    advantages: {
      headline: "",
      items: [],
    },
    useCases: {
      headline: "",
      items: [],
    },
    apiSection: {
      headline: "",
      description: "",
      apiDocumentation: {
        text: "",
        href: "",
      },
    },
    cta: {
      headline: "",
      description: "",
      primary: { text: "Request a Demo", href: "/demo" },
    },
    backgroundImage: "/GenAI.webp",
  },

  "voice-clones": {
    metadata: {
      title: "Voice Cloning — ScamAI",
      description:
        "Detect AI voice clones and synthetic audio with ScamAI's real-time detection technology.",
    },

    hero: {
      category: "AI Voice Clone Detection",
      headline: "Real-Time AI Voice Clone Detection",
      subtitle: "Secure Every Conversation",
      description:
        "Our VoiceGuard model instantly identifies synthetic speech and deepfake audio, stopping voice-based fraud in real time. It can detect synthetic audio like Sale0625.mp3, which was generated by minimax.io.",
      tags: ["Voice AI", "Audio Synthesis", "Detection", "VoiceGuard"],
      visual: {
        type: "audio",
        src: "/Sale0625.mp3",
        alt: "Example synthetic audio file Sale0625.mp3 generated by minimax.io",
      },
    },
    problemSection: {
      headline: "The Threat: Can You Trust What You Hear?",
      description: "",
      visual: {
        type: "image",
        src: "/voice-detected.png",
        alt: "Voice detection interface showing analysis results for synthetic audio",
      },
      valueProps: [],
    },
    threatLandscape: {
      headline: "",
      description: "",
      keyThreats: [],
      dataPoint: "",
    },
    solution: {
      productName: "",
      headline: "",
      description: "",
      coreDimensions: [],
      outputDescription: "",
    },
    advantages: {
      headline: "",
      items: [],
    },
    useCases: {
      headline: "",
      items: [],
    },
    apiSection: {
      headline: "",
      description: "",
      apiDocumentation: {
        text: "",
        href: "",
      },
    },
    cta: {
      headline: "Secure Your Audio Channels",
      description:
        "Protect your users from voice-based fraud and impersonation.",
      primary: { text: "Request a Demo", href: "/demo" },
    },
    backgroundImage: "/visual.webp",
    overlayColor: "bg-purple-600/32",
  },
};

// Helper function to get configuration for a specific model
export function getDetectionModelConfig(
  modelType: DetectionModelType
): ProductPageProps {
  return detectionModelsConfig[modelType];
}

// Export metadata for each model (for Next.js metadata API)
export const detectionModelsMetadata = {
  deepfakes: { title: "Deepfakes (Faceswap) — ScamAI" },
  "ai-generated-media": { title: "AI Image Detection — ScamAI" },
  "voice-clones": { title: "Voice Cloning — ScamAI" },
};
