"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";
import NewNav from "@/components/new-site/NewNav";
import NewFooter from "@/components/new-site/NewFooter";
import { trackCTA, trackOutbound } from "@/lib/analytics";

function AnimatedSection({
  children,
  className = "",
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-80px" });

  return (
    <motion.div
      ref={ref}
      initial={{ opacity: 0, y: 40 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 40 }}
      transition={{ duration: 0.7, delay, ease: [0.25, 0.1, 0.25, 1.0] }}
      className={className}
    >
      {children}
    </motion.div>
  );
}

interface Paper {
  title: string;
  authors: string;
  venue: string;
  date: string;
  tags: string[];
  abstract: string;
  link?: string;
}

const papers: Paper[] = [
  {
    title: "Eva-v1: Real-Time Deepfake Detection at Scale with Adaptive Ensemble Models",
    authors: "ScamAI Research Team",
    venue: "Internal Technical Report",
    date: "January 2026",
    tags: ["Deepfake Detection", "Eva-v1", "Real-Time"],
    abstract:
      "We introduce Eva-v1, an adaptive ensemble architecture for real-time deepfake detection across images, video, and audio. Eva-v1 combines frequency-domain analysis with transformer-based feature extraction to achieve 95.3% accuracy on FaceForensics++ while maintaining sub-200ms inference latency. We demonstrate robustness against adversarial perturbations and cross-domain generalization to unseen generative models.",
  },
  {
    title: "Synthetic Voice Detection: Benchmarking Against Modern TTS and Voice Cloning Systems",
    authors: "ScamAI Research Team",
    venue: "Internal Technical Report",
    date: "December 2025",
    tags: ["Audio", "Voice Cloning", "Benchmark"],
    abstract:
      "We evaluate detection performance against 12 state-of-the-art text-to-speech and voice cloning systems, including ElevenLabs, Resemble AI, and open-source alternatives. Our approach leverages spectro-temporal artifacts and prosodic inconsistencies to achieve 92.7% detection accuracy on held-out data, with particular strength in detecting real-time voice conversion attacks targeting call centers.",
  },
  {
    title: "Document Forgery Detection Using Multi-Scale Forensic Analysis",
    authors: "ScamAI Research Team",
    venue: "Internal Technical Report",
    date: "November 2025",
    tags: ["Document Forgery", "Forensics"],
    abstract:
      "We present a multi-scale forensic pipeline for detecting AI-generated and manipulated documents including bank statements, pay stubs, and identity documents. Our method combines pixel-level manipulation detection with semantic consistency checks to identify both traditional splicing attacks and fully synthetic documents generated by large language models.",
  },
  {
    title: "Adversarial Robustness of Deepfake Detectors: An Empirical Study",
    authors: "ScamAI Research Team",
    venue: "Internal Technical Report",
    date: "October 2025",
    tags: ["Adversarial ML", "Robustness"],
    abstract:
      "We systematically evaluate the adversarial robustness of modern deepfake detectors, including our own Eva models, against white-box and black-box attacks. We find that standard detectors degrade significantly under FGSM and PGD perturbations, and propose Adaptive Defense — a real-time adversarial detection module that identifies and mitigates evasion attempts during inference, improving robustness by 34% with minimal latency overhead.",
  },
  {
    title: "Active Liveness Detection: Preventing Presentation Attacks with Challenge-Response Protocols",
    authors: "ScamAI Research Team",
    venue: "Internal Technical Report",
    date: "September 2025",
    tags: ["Liveness", "Anti-Spoofing"],
    abstract:
      "We propose a challenge-response liveness detection framework that combines passive anti-spoofing signals with active user prompts (head turn, blink, expression) to prevent presentation attacks using printed photos, screen replays, and 3D masks. Evaluation on a dataset of 50,000 attack samples shows 99.2% spoof rejection rate with a 0.3% false rejection rate on legitimate users.",
  },
];

const stats = [
  { label: "Detection Accuracy", value: "95.3%" },
  { label: "Inference Latency", value: "<200ms" },
  { label: "Attack Types Covered", value: "50+" },
  { label: "Models Benchmarked", value: "30+" },
];

export default function ResearchPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <NewNav />

      <main className="pt-[140px] sm:pt-[160px]">
        {/* Hero */}
        <section className="mx-auto max-w-6xl px-4 sm:px-8 pb-14 sm:pb-20">
          <AnimatedSection>
            <div className="max-w-3xl">
              <p className="text-[9px] font-semibold uppercase tracking-[0.16em] text-[#245FFF] mb-3 sm:text-[10px] lg:mb-4">
                RESEARCH
              </p>
              <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white leading-[1.15] mb-4 lg:mb-6">
                Advancing the science of{" "}
                <span className="text-[#245FFF]">AI trust</span>
              </h1>
              <p className="text-sm sm:text-base text-gray-500 leading-relaxed max-w-xl">
                Our research focuses on deepfake detection, synthetic media forensics, and adversarial
                robustness. We publish our findings to advance the field and keep our customers ahead of
                emerging threats.
              </p>
            </div>
          </AnimatedSection>

          {/* Stats */}
          <AnimatedSection delay={0.15}>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-10 lg:mt-14">
              {stats.map((stat) => (
                <div
                  key={stat.label}
                  className="rounded-xl border border-gray-800/60 bg-white/[0.02] p-4 sm:p-5"
                >
                  <p className="text-2xl sm:text-3xl font-bold text-white mb-1">{stat.value}</p>
                  <p className="text-xs text-gray-500">{stat.label}</p>
                </div>
              ))}
            </div>
          </AnimatedSection>
        </section>

        <div className="section-divider" />

        {/* Papers */}
        <section className="mx-auto max-w-6xl px-4 sm:px-8 py-14 sm:py-20">
          <AnimatedSection>
            <div className="mb-8 lg:mb-12">
              <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white mb-2">
                Publications & Reports
              </h2>
              <p className="text-sm text-gray-500">
                Technical reports from the ScamAI research team.
              </p>
            </div>
          </AnimatedSection>

          <div className="space-y-4">
            {papers.map((paper, index) => (
              <AnimatedSection key={paper.title} delay={0.08 * (index + 1)}>
                <article className="group rounded-xl sm:rounded-2xl border border-gray-800/60 bg-white/[0.02] p-5 sm:p-7 transition-all duration-300 hover:border-[#245FFF]/20 hover:bg-white/[0.04]">
                  <div className="flex flex-wrap items-center gap-2 mb-3">
                    {paper.tags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded-full bg-[#245FFF]/10 px-2.5 py-0.5 text-[10px] font-semibold text-[#245FFF]"
                      >
                        {tag}
                      </span>
                    ))}
                    <span className="text-[10px] text-gray-600 ml-auto">{paper.date}</span>
                  </div>

                  <h3 className="text-base sm:text-lg font-semibold text-white mb-1.5 leading-snug group-hover:text-[#245FFF] transition-colors">
                    {paper.title}
                  </h3>

                  <p className="text-xs text-gray-500 mb-3">
                    {paper.authors} &middot; {paper.venue}
                  </p>

                  <p className="text-xs sm:text-sm text-gray-400 leading-relaxed">
                    {paper.abstract}
                  </p>

                  {paper.link && (
                    <a
                      href={paper.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1.5 mt-4 text-xs font-semibold text-[#245FFF] hover:gap-2.5 transition-all"
                    >
                      Read paper
                      <svg className="h-3 w-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                      </svg>
                    </a>
                  )}
                </article>
              </AnimatedSection>
            ))}
          </div>
        </section>

        <div className="section-divider" />

        {/* Datasets */}
        <section className="mx-auto max-w-6xl px-4 sm:px-8 py-14 sm:py-20">
          <AnimatedSection>
            <div className="mb-8 lg:mb-12">
              <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white mb-2">
                Open Datasets
              </h2>
              <p className="text-sm text-gray-500 max-w-xl">
                We release curated datasets to help researchers benchmark deepfake detection models.
                All datasets are available for non-commercial research use.
              </p>
            </div>
          </AnimatedSection>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {([
              {
                name: "ScamAI-Faces-v1",
                size: "12,400 images",
                format: "PNG + JSON annotations",
                description: "Paired real and deepfake face images from 15 generation methods including face swap, face reenactment, and fully synthetic faces. Includes manipulation metadata and source model labels.",
                tags: ["Face Deepfake", "Image"],
                downloadSize: "4.2 GB",
              },
              {
                name: "ScamAI-Voices-v1",
                size: "8,600 audio clips",
                format: "WAV + JSON annotations",
                description: "Real and cloned voice samples from 12 TTS/voice cloning systems. Covers multiple languages, genders, and attack scenarios including real-time voice conversion and zero-shot cloning.",
                tags: ["Voice Clone", "Audio"],
                downloadSize: "2.8 GB",
              },
              {
                name: "ScamAI-Docs-v1",
                size: "5,200 documents",
                format: "PDF/PNG + JSON annotations",
                description: "Authentic and forged documents including bank statements, IDs, pay stubs, and certificates. Includes both traditional manipulation (splicing, editing) and fully AI-generated documents.",
                tags: ["Document Forgery", "Multi-format"],
                downloadSize: "1.6 GB",
              },
              {
                name: "ScamAI-Liveness-v1",
                size: "50,000 video clips",
                format: "MP4 + JSON annotations",
                description: "Presentation attack dataset covering printed photos, screen replays, 3D masks, and deepfake video attacks. Captured across diverse lighting, devices, and demographics.",
                tags: ["Liveness", "Video"],
                downloadSize: "18.5 GB",
              },
              {
                name: "ScamAI-Adversarial-v1",
                size: "6,000 samples",
                format: "PNG + adversarial metadata",
                description: "Adversarially perturbed deepfakes designed to evade detection. Includes FGSM, PGD, and custom evasion attacks with perturbation budgets and attack success rates.",
                tags: ["Adversarial", "Benchmark"],
                downloadSize: "2.1 GB",
              },
              {
                name: "ScamAI-GenAI-v1",
                size: "20,000 images",
                format: "PNG + generation metadata",
                description: "AI-generated images from 25+ models including Stable Diffusion, DALL-E 3, Midjourney, and Flux. Labeled with source model, prompt category, and generation parameters.",
                tags: ["GenAI", "Image"],
                downloadSize: "7.3 GB",
              },
            ]).map((dataset, index) => (
              <AnimatedSection key={dataset.name} delay={0.08 * (index + 1)}>
                <div className="group flex flex-col h-full rounded-xl sm:rounded-2xl border border-gray-800/60 bg-white/[0.02] p-5 sm:p-6 transition-all duration-300 hover:border-[#245FFF]/20 hover:bg-white/[0.04]">
                  {/* Tags */}
                  <div className="flex flex-wrap gap-1.5 mb-3">
                    {dataset.tags.map((tag) => (
                      <span
                        key={tag}
                        className="rounded-full bg-white/5 border border-gray-800/60 px-2 py-0.5 text-[10px] font-medium text-gray-400"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  {/* Name */}
                  <h3 className="text-sm sm:text-base font-semibold text-white mb-1 group-hover:text-[#245FFF] transition-colors">
                    {dataset.name}
                  </h3>

                  {/* Meta */}
                  <div className="flex items-center gap-3 mb-3 text-[11px] text-gray-600">
                    <span>{dataset.size}</span>
                    <span className="w-px h-3 bg-gray-800" />
                    <span>{dataset.format}</span>
                  </div>

                  {/* Description */}
                  <p className="text-xs text-gray-500 leading-relaxed mb-5 flex-1">
                    {dataset.description}
                  </p>

                  {/* Download button */}
                  <button
                    onClick={() => {
                      trackOutbound(`dataset:${dataset.name}`, "dataset_download");
                      // Request access flow — opens a form or email
                      window.open("https://cal.com/scamai/15min", "_blank", "noopener,noreferrer");
                    }}
                    className="w-full flex items-center justify-center gap-2 rounded-lg border border-gray-800/60 bg-white/[0.03] px-4 py-2.5 text-xs font-semibold text-white transition-all hover:border-[#245FFF]/30 hover:bg-[#245FFF]/5 hover:text-[#245FFF]"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                    </svg>
                    Request Access ({dataset.downloadSize})
                  </button>
                </div>
              </AnimatedSection>
            ))}
          </div>

          {/* License note */}
          <AnimatedSection delay={0.6}>
            <div className="mt-8 rounded-xl border border-gray-800/60 bg-white/[0.02] p-5 flex items-start gap-3">
              <svg className="w-5 h-5 text-gray-600 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <div>
                <p className="text-xs font-semibold text-white mb-1">Usage License</p>
                <p className="text-xs text-gray-500 leading-relaxed">
                  All datasets are released under the <strong className="text-gray-400">ScamAI Research License</strong> for
                  non-commercial academic and research purposes. Commercial use requires a separate license agreement.
                  Please cite our work if you use these datasets in your publications.
                </p>
              </div>
            </div>
          </AnimatedSection>
        </section>

        <div className="section-divider" />

        {/* CTA */}
        <section className="mx-auto max-w-6xl px-4 sm:px-8 py-14 sm:py-20">
          <AnimatedSection>
            <div className="text-center">
              <h2 className="text-xl sm:text-2xl font-bold text-white mb-3">
                Interested in collaborating?
              </h2>
              <p className="text-sm text-gray-500 mb-6 max-w-md mx-auto">
                We partner with academic institutions and industry labs on deepfake detection research.
              </p>
              <a
                href="https://cal.com/scamai/15min"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 rounded-full bg-[#245FFF] px-7 py-3 text-sm font-semibold text-white transition-all hover:bg-[#1d4acc]"
              >
                Get in touch
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M5 12h14" />
                  <path d="M12 5l7 7-7 7" />
                </svg>
              </a>
            </div>
          </AnimatedSection>
        </section>
      </main>

      <NewFooter />
    </div>
  );
}
