"use client";

interface ChangelogEntry {
  date: string;
  version: string;
  title: string;
  tags: string[];
  description: string;
}

const changelogData: ChangelogEntry[] = [
  {
    date: "February 2, 2026",
    version: "3.0",
    title: "No-Code Platform & Self-Serve Launch",
    tags: ["Platform", "Product"],
    description: "Introduced no-code detection platform with drag-and-drop interface. Self-serve onboarding enables users to start detecting deepfakes in minutes without technical setup or API integration."
  },
  {
    date: "January 15, 2026",
    version: "2.1",
    title: "Enhanced Detection Accuracy",
    tags: ["AI", "Performance"],
    description: "Improved deepfake detection accuracy to 95.3% with reduced processing time to under 200ms. Added support for 4K video analysis and enhanced audio deepfake detection algorithms."
  },
  {
    date: "December 15, 2025",
    version: "■",
    title: "Seed Funding Round - $2.5M",
    tags: ["Funding", "Milestone"],
    description: "Closed $2.5M in total equity financing led by Llama Venture, with participation from SCVxSBI, Welight Capital, SkyDeck Fund, and Beta Fund. Funding will accelerate product development and global expansion."
  },
  {
    date: "December 10, 2025",
    version: "2.0",
    title: "GenAI Detection Release",
    tags: ["AI", "New Feature"],
    description: "Launched comprehensive GenAI content detection across text, images, and videos. Advanced AI models identify content generated by ChatGPT, Midjourney, DALL-E, and other generative AI platforms."
  },
  {
    date: "November 5, 2025",
    version: "1.5",
    title: "Audio Detection Release",
    tags: ["Audio", "New Feature"],
    description: "Launched audio deepfake detection with 92% accuracy for voice cloning. Support for MP3, WAV, and AAC formats with real-time audio stream analysis."
  },
  {
    date: "August 25, 2025",
    version: "◆",
    title: "GDPR and SOC 2 Type I Compliance",
    tags: ["Security", "Compliance"],
    description: "Achieved GDPR compliance and SOC 2 Type I certification, demonstrating our commitment to data privacy and security. Enterprise-grade security standards now in place."
  },
  {
    date: "May 15, 2025",
    version: "■",
    title: "Pre-Seed Funding from Berkeley SkyDeck",
    tags: ["Funding", "Milestone"],
    description: "Selected for Berkeley SkyDeck, UC Berkeley's premier deep-tech accelerator program with less than 1% acceptance rate. Received investment to accelerate our mission of combating synthetic media threats."
  },
  {
    date: "January 31, 2025",
    version: "★",
    title: "Product Hunt - Product of the Day",
    tags: ["Award", "Milestone"],
    description: "ScamAI was recognized as Product of the Day on Product Hunt! Thank you to our amazing community for the support and feedback."
  },
  {
    date: "January 5, 2025",
    version: "0.1",
    title: "Deepfake Detection Model v0.1 Launched",
    tags: ["Launch", "AI"],
    description: "Released our first deepfake detection model to the public. Initial version focuses on image and video analysis with foundational AI capabilities for synthetic media detection."
  }
];

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-black text-white">
      {/* Hero Section */}
      <section className="relative px-4 sm:px-6" style={{ paddingTop: '180px', paddingBottom: '60px' }}>
        <div className="mx-auto max-w-5xl text-center">
          <h1 className="mb-8 text-5xl font-semibold sm:text-6xl lg:text-7xl tracking-tight leading-[1.1]">
            Building trust<br />in the AI era.
          </h1>
        </div>
      </section>

      {/* Mission Section */}
      <section className="py-16 px-4 sm:px-6">
        <div className="mx-auto max-w-4xl">
          <h2 className="mb-8 text-3xl sm:text-4xl font-semibold">Our Mission</h2>
          <div className="space-y-6 text-lg text-gray-300 leading-relaxed">
            <p>
              As AI-generated content becomes increasingly sophisticated, the line between real and fake is blurring. Deepfakes and synthetic media threaten trust, security, and truth across industries.
            </p>
            <p>
              ScamAI was founded to solve this critical challenge. We provide the most accurate, fastest, and most accessible deepfake detection platform in the world.
            </p>
            <p>
              Our technology protects users across social media, financial services, media organizations, and enterprises worldwide.
            </p>
          </div>
        </div>
      </section>

      {/* Milestone Section */}
      <section className="py-16 px-4 sm:px-6 border-t border-gray-800" style={{ paddingBottom: '120px' }}>
        <div className="mx-auto max-w-4xl">
          <h2 className="mb-12 text-3xl sm:text-4xl font-semibold">Milestone</h2>
          
          <div className="relative">
            {changelogData.map((entry, index) => (
              <div key={entry.version} className="relative pb-12 last:pb-0">
                <div className="flex gap-6">
                  {/* Dot */}
                  <div className="flex-shrink-0 relative">
                    <div className="w-3 h-3 bg-white rounded-full mt-1.5" />
                    {/* Vertical Line */}
                    {index < changelogData.length - 1 && (
                      <div className="absolute left-1/2 top-6 w-px h-[calc(100%+36px)] bg-gray-800 -translate-x-1/2" />
                    )}
                  </div>

                  {/* Content */}
                  <div className="flex-1 relative">
                    
                    <div className="space-y-3">
                      <div>
                        <time className="text-sm text-gray-400">{entry.date}</time>
                        <h3 className="text-xl font-semibold mt-1">{entry.title}</h3>
                      </div>
                      
                      {/* Tags */}
                      <div className="flex flex-wrap gap-2">
                        {entry.tags.map((tag) => (
                          <span
                            key={tag}
                            className="px-2.5 py-1 text-xs font-medium bg-gray-800 text-gray-300 rounded-full border border-gray-700"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                      
                      <p className="text-gray-400 leading-relaxed">
                        {entry.description}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
