export type IsAiEntry = {
  slug: string;
  subject: string;                // "Pope in a puffer jacket"
  verdict: "ai_generated" | "real" | "mixed" | "uncertain";
  confidenceLabel: string;        // "High confidence"
  short: string;                  // 1-sentence summary (shown in grid + hero)
  context: string;                // 1-2 paragraphs unique context
  signals: string[];              // bullet list of what Eva found
  published: string;              // ISO date
  categories: string[];           // tags, used for related links
  sourceUrl?: string;
};

export const IS_AI_ENTRIES: IsAiEntry[] = [
  {
    slug: "pope-puffer-jacket",
    subject: "Pope Francis in a white puffer jacket",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "The viral 2023 image of Pope Francis wearing a Balenciaga-style puffer jacket is AI-generated via Midjourney v5.",
    context:
      "The image first appeared on Reddit's r/midjourney in March 2023, uploaded by a Chicago construction worker who used Midjourney v5 to generate it. It went viral across X, Instagram, and WhatsApp with millions believing it was a genuine paparazzi shot. Eva V1.6 scores the image with strong diffusion-model signals, soft edges around the crucifix chain, and texture artifacts in the jacket — all classic Midjourney tells.",
    signals: [
      "Diffusion model artifacts in fabric texture (score: 94)",
      "Inconsistent lighting on crucifix chain",
      "Soft, hallucinated ear geometry",
      "Background depth-of-field is too uniform for a real photo",
    ],
    published: "2026-04-17",
    categories: ["celebrity", "viral-meme", "midjourney"],
    sourceUrl: "https://www.theguardian.com/technology/2023/mar/27/pope-francis-puffer-jacket-ai-image-viral-midjourney",
  },
  {
    slug: "shrimp-jesus",
    subject: "Shrimp Jesus Facebook posts",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "The Shrimp Jesus images flooding Facebook are AI-generated — likely Midjourney or a similar diffusion model — designed to harvest engagement.",
    context:
      "The Shrimp Jesus meme is a large-scale AI engagement-farm on Facebook Pages. Hundreds of variants show a Christ-like figure fused with shrimp or crustacean bodies, usually accompanied by emotional captions. Eva scores the images with strong diffusion artifacts and geometric impossibilities. The accounts posting them are part of a larger pattern of AI spam identified by Stanford's Internet Observatory.",
    signals: [
      "Impossible shrimp anatomy with human proportions",
      "Diffusion model texture across both organic surfaces",
      "Inconsistent lighting between Christ figure and shrimp",
      "Artificially symmetric composition",
    ],
    published: "2026-04-17",
    categories: ["viral-meme", "facebook-spam", "engagement-farm"],
    sourceUrl: "https://cyber.fsi.stanford.edu/io/news/how-spammers-and-scammers-leverage-ai-generated-images-facebook-reach",
  },
  {
    slug: "taylor-swift-sora-concert",
    subject: "Taylor Swift Sora concert footage",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "The 'unseen concert footage' of Taylor Swift circulating on X is generated by OpenAI's Sora, not captured live.",
    context:
      "A series of short clips claiming to show never-before-seen Taylor Swift concert footage from 2024 went viral on X in early 2026. Eva V1.6 flags the clips as Sora-generated output based on temporal flickering in crowd details, unnatural microphone physics, and audience faces that morph between frames — all hallmarks of current diffusion video models.",
    signals: [
      "Temporal flickering in crowd faces across frames",
      "Unnatural microphone-hand interaction",
      "Inconsistent stage lighting frame-to-frame",
      "Audience limb counts change between cuts",
    ],
    published: "2026-04-17",
    categories: ["celebrity", "sora", "video", "concert"],
  },
  {
    slug: "trump-mugshot-fulton-county",
    subject: "Donald Trump Fulton County mugshot (August 2023)",
    verdict: "real",
    confidenceLabel: "High confidence",
    short: "The August 2023 Fulton County booking photo of Donald Trump is a real, officially released mugshot — not AI-generated.",
    context:
      "Despite social-media speculation, the Fulton County Sheriff's Office officially released the booking photo after Trump's surrender on August 24, 2023. Eva V1.6 finds no diffusion or GAN signals, and the EXIF metadata, lighting consistency, and sensor-noise signature all match a typical institutional camera. We publish this as a real-negative example — confident verdicts both ways matter.",
    signals: [
      "Consistent sensor noise across the frame",
      "Realistic fabric-shadow interaction",
      "No detected diffusion or GAN artifacts",
      "Metadata consistent with institutional camera",
    ],
    published: "2026-04-17",
    categories: ["politics", "mugshot", "real-negative"],
    sourceUrl: "https://www.fultoncountyga.gov/news/2023/08/24/booking-photo-donald-trump",
  },
  {
    slug: "will-smith-eating-spaghetti",
    subject: "Will Smith eating spaghetti (Gen-2 2023 clip)",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "The infamous 2023 'Will Smith eating spaghetti' clip is an early Runway Gen-2 output — obviously synthetic, but still shared as a benchmark for how fast video generation improved.",
    context:
      "The clip went viral for how uncanny the output was — morphing facial geometry, spaghetti-physics violating causality, plate reshaping between frames. It's now the textbook benchmark for how quickly diffusion video caught up (Sora, Veo, Kling all produce radically better outputs in 2026). Eva scores this at >99% AI confidence.",
    signals: [
      "Facial landmarks morph continuously",
      "Spaghetti strands teleport between frames",
      "Plate geometry reshapes throughout clip",
      "Impossible chewing mechanics",
    ],
    published: "2026-04-17",
    categories: ["video", "celebrity", "historical-benchmark"],
  },
  {
    slug: "elon-musk-crypto-endorsement",
    subject: "Elon Musk crypto-giveaway deepfake videos",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "The Elon Musk videos promising 'double your Bitcoin' are deepfake scams — face-swap overlays on real Musk footage combined with voice cloning.",
    context:
      "An entire scam industry has grown around deepfaked Musk endorsements. Typical pattern: real footage of Musk (from interviews, TED talks, Tesla events) with face-swap alignment adjustments and cloned voice dubs saying 'send crypto to this wallet, I'll send back double.' Eva V1.6 reliably flags these — face-swap boundary artifacts around the jaw, voice spectrogram discontinuities, and eye-blink patterns that don't match the original footage.",
    signals: [
      "Face-swap seam artifacts along jaw/hairline",
      "Eye-blink frequency inconsistent with source",
      "Voice spectrogram shows clone-model signatures",
      "Lip-sync drift from audio",
    ],
    published: "2026-04-17",
    categories: ["deepfake-scam", "crypto-scam", "face-swap"],
  },
  {
    slug: "romance-scam-profile-photos",
    subject: "AI-generated dating profile photos used in romance scams",
    verdict: "ai_generated",
    confidenceLabel: "High confidence",
    short: "A large fraction of 'too good to be true' dating profile photos used in romance scams are AI-generated — typically StyleGAN or ThisPersonDoesNotExist-style outputs.",
    context:
      "Romance scams — projected by the FBI IC3 to cost U.S. victims over $1.3B in 2024 — heavily rely on AI-generated profile photos. Telltale signs: the face is perfectly centered, hair has synthetic blurs near the scalp, and reverse image searches turn up nothing. Eva V1.6 catches the vast majority of these with StyleGAN-family signal detection, plus metadata checks.",
    signals: [
      "Perfect face-centering (StyleGAN alignment)",
      "Symmetric earring / eye mismatches",
      "Backdrop bokeh doesn't match real camera",
      "No reverse-image-search matches",
    ],
    published: "2026-04-17",
    categories: ["romance-scam", "dating", "stylegan", "consumer-protection"],
  },
];

export function getIsAiBySlug(slug: string): IsAiEntry | null {
  return IS_AI_ENTRIES.find((e) => e.slug === slug) ?? null;
}

export function getIsAiRelated(slug: string, max = 3): IsAiEntry[] {
  const me = getIsAiBySlug(slug);
  if (!me) return IS_AI_ENTRIES.slice(0, max);
  const scored = IS_AI_ENTRIES.filter((e) => e.slug !== slug).map((e) => ({
    entry: e,
    overlap: e.categories.filter((c) => me.categories.includes(c)).length,
  }));
  scored.sort((a, b) => b.overlap - a.overlap);
  return scored.slice(0, max).map((s) => s.entry);
}
