"use client";

import React, { useState } from "react";
import Image from "next/image";

function HeroSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4 text-center">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white">
          Real-Time AI Voice Clone Detection: Secure Every Conversation
        </h1>
        <p className="mt-4 text-lg text-white/80 max-w-3xl mx-auto">
          Scam.ai&apos;s cutting-edge voice clone detection model instantly identifies synthetic speech and deepfake audio, stopping fraud before it happens.
        </p>
      </div>
    </section>
  );
}

function InteractiveAudioPlayer() {
  const [played, setPlayed] = useState<{ elon: boolean; morgan: boolean }>({ elon: false, morgan: false });
  const [isPlaying, setIsPlaying] = useState<null | "elon" | "morgan" | "none">(null);

  const simulatePlay = (who: "elon" | "morgan") => {
    if (isPlaying) return;
    setIsPlaying(who);
    setTimeout(() => {
      setPlayed((prev) => ({ ...prev, [who]: true }));
      setIsPlaying(null);
    }, 1500);
  };

  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">
          Listen For Yourself: Can You Tell Real From AI?
        </h2>
        <p className="mt-4 text-lg text-white/80 text-center max-w-3xl mx-auto">
          Hear our technology in action. The audio clips below were generated by AI and detected by our model in real-time.
        </p>

        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Example 1: Elon */}
          <div className="rounded-lg border border-white/10 bg-white/5 p-6">
            <div className="flex items-start gap-4">
              <div className="shrink-0 text-3xl" aria-hidden>👤</div>
              <div className="flex-1">
                <p className="text-white">
                  &quot;Scam.ai has built some truly impressive technology. It&apos;s essential for trust and safety on any platform.&quot;
                </p>
                <button
                  type="button"
                  onClick={() => simulatePlay("elon")}
                  className="mt-4 inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60"
                  disabled={isPlaying !== null}
                >
                  <span aria-hidden>▶️</span>
                  {isPlaying === "elon" ? "Playing..." : "Play"}
                </button>
                {played.elon && (
                  <div className="mt-2 rounded-md bg-red-500/20 p-2 text-sm font-semibold text-red-300">
                    DETECTED: AI CLONE (99.6% Confidence)
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Example 2: Morgan */}
          <div className="rounded-lg border border-white/10 bg-white/5 p-6">
            <div className="flex items-start gap-4">
              <div className="shrink-0 text-3xl" aria-hidden>👤</div>
              <div className="flex-1">
                <p className="text-white">
                  &quot;Some things should never be faked. The human voice is one of them.&quot;
                </p>
                <button
                  type="button"
                  onClick={() => simulatePlay("morgan")}
                  className="mt-4 inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 font-semibold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-60"
                  disabled={isPlaying !== null}
                >
                  <span aria-hidden>▶️</span>
                  {isPlaying === "morgan" ? "Playing..." : "Play"}
                </button>
                {played.morgan && (
                  <div className="mt-2 rounded-md bg-red-500/20 p-2 text-sm font-semibold text-red-300">
                    DETECTED: AI CLONE (99.6% Confidence)
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function ThreatLandscapeSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">
          The Threat is Here: Can You Trust What You Hear?
        </h2>
        <div className="mt-8 rounded-lg bg-white/5 border border-white/10 p-4 grid place-items-center">
          {/* Placeholder for dynamic soundwave visual */}
          <Image
            src="/visual.webp"
            alt="Soundwave visual placeholder"
            width={640}
            height={128}
            className="h-32 w-auto object-contain opacity-70"
          />
        </div>
        <p className="mt-6 text-lg text-white/80">
          With as little as a 3-second audio sample, modern generative models can synthesize convincing voice clones that are nearly indistinguishable to the human ear. This introduces critical risks across financial services, enterprise operations, and personal communications, where trust and authenticity are paramount.
        </p>

        <div className="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="flex items-start gap-3 rounded-lg bg-white/5 p-4">
            <span aria-hidden>💵</span>
            <div>
              <p className="font-semibold text-white">Financial Fraud (Vishing)</p>
              <p className="text-sm text-white/80">Attackers use voice clones to socially engineer victims and authorize fraudulent transactions.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 rounded-lg bg-white/5 p-4">
            <span aria-hidden>🏢</span>
            <div>
              <p className="font-semibold text-white">Corporate & Internal Fraud</p>
              <p className="text-sm text-white/80">Executive impersonation and vendor spoofing expose organizations to high-risk payouts.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 rounded-lg bg-white/5 p-4">
            <span aria-hidden>🚨</span>
            <div>
              <p className="font-semibold text-white">Personal Attacks</p>
              <p className="text-sm text-white/80">Highly targeted harassment and extortion campaigns leverage synthetic audio for intimidation.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 rounded-lg bg-white/5 p-4">
            <span aria-hidden>📣</span>
            <div>
              <p className="font-semibold text-white">Disinformation Campaigns</p>
              <p className="text-sm text-white/80">Coordinated synthetic content erodes public trust and amplifies misinformation at scale.</p>
            </div>
          </div>
        </div>

        <p className="mt-6 text-sm text-white/60">
          Data Point: Voice clone attacks are rapidly increasing across industries. <a href="#" className="underline underline-offset-4 text-blue-400">(Source: Placeholder)</a>
        </p>
        <p className="mt-2 text-sm text-blue-400 font-semibold">
          <a href="#" className="hover:underline">See real-world case studies of voice cloning fraud here -&gt;</a>
        </p>
      </div>
    </section>
  );
}

function SolutionSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">Our Solution: The Auditory Guardian™</h2>
        <div className="mt-8 rounded-lg bg-white/5 border border-white/10 p-4 grid place-items-center">
          {/* Placeholder for architecture diagram */}
          <Image
            src="/visual.webp"
            alt="Auditory Guardian diagram placeholder"
            width={640}
            height={128}
            className="h-32 w-auto object-contain opacity-70"
          />
        </div>
        <p className="mt-6 text-lg text-white/80">
          Scam.ai&apos;s Auditory Guardian™ is an intelligent defense system purpose-built to detect synthetic speech. It analyzes the acoustic and spectral footprint of audio to uncover the microscopic traces left by generative models—going far beyond human perception.
        </p>

        <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="text-lg font-semibold text-white">Acoustic Fingerprinting</h4>
            <p className="mt-2 text-sm text-white/80">Identifies unique timbral and phase characteristics introduced during synthesis, revealing non-human production artifacts.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="text-lg font-semibold text-white">Spectrogram Anomaly Detection</h4>
            <p className="mt-2 text-sm text-white/80">Locates unnatural harmonics, temporal smearing, and spectral inconsistencies that diverge from organic speech patterns.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="text-lg font-semibold text-white">Generative Artifact Recognition</h4>
            <p className="mt-2 text-sm text-white/80">Detects telltale signatures of specific model families and pipelines, helping attribute likely generation methods.</p>
          </div>
        </div>

        <p className="mt-6 text-sm text-white/70">
          Result: Each analysis returns a Trust Score with supporting evidence, enabling rapid triage, escalation, or automated action within your workflows.
        </p>
      </div>
    </section>
  );
}

function AdvantagesSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">Our Advantage: Why Choose Auditory Guardian™?</h2>
        <div className="mt-10 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <span aria-hidden>⚡</span>
              <h4 className="font-semibold text-white">Millisecond-Level Response</h4>
            </div>
            <p className="mt-2 text-sm text-white/80">Low-latency detection suitable for live communication and contact centers.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <span aria-hidden>🎯</span>
              <h4 className="font-semibold text-white">Unparalleled Accuracy</h4>
            </div>
            <p className="mt-2 text-sm text-white/80">Trained on diverse datasets for high precision across accents and environments.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <span aria-hidden>🛡️</span>
              <h4 className="font-semibold text-white">Exceptional Robustness</h4>
            </div>
            <p className="mt-2 text-sm text-white/80">Resilient to compression, noise, and transmission artifacts common in real-world audio.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <div className="flex items-center gap-3">
              <span aria-hidden>🧠</span>
              <h4 className="font-semibold text-white">Constantly Evolving</h4>
            </div>
            <p className="mt-2 text-sm text-white/80">Continuously updated models that adapt to the latest cloning techniques.</p>
          </div>
        </div>
      </div>
    </section>
  );
}

function CommandCenterSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">Unified Command Center: A Panoramic View of Risk</h2>
        <div className="mt-8 rounded-lg bg-white/5 border border-white/10 shadow p-4 grid place-items-center">
          <Image src="/visual.webp" alt="Command center dashboard placeholder" width={680} height={160} className="h-40 w-auto object-contain opacity-70" />
        </div>
        <p className="mt-6 text-lg text-white/80">
          There&apos;s no need to switch between systems. Centralize detection, investigation, and response with a unified command center tailored to your operational needs.
        </p>
        <ul className="mt-6 space-y-3">
          <li className="flex items-start gap-3 text-white/80">
            <span aria-hidden>✅</span>
            <span className="text-white/80"><strong>Global Perspective:</strong> A one-stop view of voice-based threats across regions, channels, and teams.</span>
          </li>
          <li className="flex items-start gap-3 text-white/80">
            <span aria-hidden>✅</span>
            <span className="text-white/80"><strong>Rapid Response:</strong> Go from threat discovery to automated remediation in seconds.</span>
          </li>
          <li className="flex items-start gap-3 text-white/80">
            <span aria-hidden>✅</span>
            <span className="text-white/80"><strong>Deep Tracing:</strong> Correlate and analyze alerts across entities, sessions, and devices.</span>
          </li>
        </ul>
      </div>
    </section>
  );
}

function UseCasesSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">Use Cases: Empowering Industries</h2>
        <div className="mt-10 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="font-semibold text-white">Banking & Finance</h4>
            <p className="mt-2 text-sm text-white/80">Prevent vishing, account takeover, and fraudulent wire transfers with real-time detection.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="font-semibold text-white">Corporate Communications Security</h4>
            <p className="mt-2 text-sm text-white/80">Verify executive and vendor communications to stop spoofed authorizations.</p>
          </div>
          <div className="rounded-lg bg:white/5 bg-white/5 p-6 shadow-sm">
            <h4 className="font-semibold text-white">Social Media & Content Platforms</h4>
            <p className="mt-2 text-sm text-white/80">Detect and label synthetic audio to preserve community trust and safety.</p>
          </div>
          <div className="rounded-lg bg-white/5 p-6 shadow-sm">
            <h4 className="font-semibold text-white">Intelligent Contact Centers</h4>
            <p className="mt-2 text-sm text-white/80">Protect agents and customers with automatic screening of inbound and outbound calls.</p>
          </div>
        </div>
        <p className="mt-6 text-sm text-blue-400 font-semibold">
          <a href="#" className="hover:underline">Explore more case studies -&gt;</a>
        </p>
      </div>
    </section>
  );
}

function ApiIntegrationSection() {
  const request = `POST /v1/audio/detect\nContent-Type: application/json\n\n{\n  "asset_uri": "https://example.com/call.wav"\n}`;
  const response = `HTTP/1.1 200 OK\n\n{\n  "request_id": "aud-xyz-123",\n  "is_clone": true,\n  "confidence_score": 0.996,\n  "evidence": [\n    {\n      "segment": [2.5, 5.7],\n      "reason_code": "spectral_inconsistency"\n    }\n  ]\n}`;

  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4">
        <h2 className="text-3xl font-bold text-center text-white">Seamless Integration, Instant Deployment</h2>
        <p className="mt-4 text-lg text-white/80 text-center max-w-3xl mx-auto">
          With our well-designed REST API, integrate AI voice clone detection in minutes, not months. Built for developer productivity and enterprise scale.
        </p>
        <div className="mt-10 grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="rounded-lg bg-slate-900 text-gray-200 p-4">
            <div className="text-sm text-gray-400 font-mono">API Request</div>
            <pre className="mt-2 overflow-auto text-sm font-mono"><code>{request}</code></pre>
          </div>
          <div className="rounded-lg bg-slate-900 text-gray-200 p-4">
            <div className="text-sm text-gray-400 font-mono">API Response</div>
            <pre className="mt-2 overflow-auto text-sm font-mono"><code>{response}</code></pre>
          </div>
        </div>
      </div>
    </section>
  );
}

function CtaSection() {
  return (
    <section className="py-20">
      <div className="max-w-5xl mx-auto px-4 text-center">
        <h2 className="text-3xl font-bold text-white">Take the Next Step</h2>
        <div className="mt-8 flex items-center justify-center gap-3">
          <a href="/request-demo" className="inline-flex items-center justify-center rounded-lg bg-blue-600 px-5 py-3 text-white font-bold hover:bg-blue-700">
            Request a Demo
          </a>
          <a href="/api-docs" className="inline-flex items-center justify-center rounded-lg bg-gray-200 px-5 py-3 text-gray-800 font-bold hover:bg-gray-300">
            View API Docs
          </a>
        </div>
      </div>
    </section>
  );
}

export default function VoiceCloneProductPage() {
  return (
    <main className="max-w-5xl mx-auto px-4">
      <HeroSection />
      <InteractiveAudioPlayer />
      <ThreatLandscapeSection />
      <SolutionSection />
      <AdvantagesSection />
      <CommandCenterSection />
      <UseCasesSection />
      <ApiIntegrationSection />
      <CtaSection />
    </main>
  );
}
